version: '3'

services:
  peigobd:
    image: 'mysql:8.0.30'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./my-datavolume:/var/lib/mysql
      - "./resources/init.sql:/docker-entrypoint-initdb.d/1.sql"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
    restart: always
  backendserver:
    build: ./peigobackend/
    ports:
      - "9000:9000"
    links:
      - "peigobd"
    depends_on:
      - "peigobd"
    restart: always
  frontend:
    build: ./peigofrontend/
    links:
      - "backendserver"
    depends_on:
      - "backendserver"
    ports:
      - "80:80"