version: '3'

services:
  db:
    image: 'mysql:8.0.30'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=peigobd
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./my-datavolume:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
    restart: always
  backendserver:
    build: ./peigobackend/
    ports:
      - "9000"
    links:
      - "db"
    depends_on:
      - "db"
    restart: always
  frontend:
    build: ./peigofrontend/
    links:
      - "backendserver"
    depends_on:
      - "backendserver"
    ports:
      - "80:80"